apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hq6r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hq6r
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-hq6r
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hq6r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hq6r
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eupe-tenant/rhtap-demo-app/hacbs-test-project-hq6r@sha256:b10b4f38778f4a0eb02e0f9ba02dc624bf9625b72be1eb0ac776f098c9aa7470
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
